[package]
name = "image-atlas"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies]
rustc-serialize = "*"
image = "*"
bincode = "0.3.0"

[dependencies.fontcache]
path = "../"

[lib]
name = "image_atlas"
