[package]
name = "fontcache"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies.glyph_packer]
git = "https://github.com/TyOverby/glyph_packer.git"

[dependencies.rustc-serialize]
